
 4221746 
Traceback (most recent call last):
  File "main.py", line 56, in main
  File "/flash/lib/ds18x20_single.py", line 14, in __init__
AssertionError: Not (only) one sensor on the bus

 4720320 
Traceback (most recent call last):
  File "main.py", line 56, in main
  File "/flash/lib/ds18x20_single.py", line 14, in __init__
AssertionError: Not (only) one sensor on the bus

 4735696 
Traceback (most recent call last):
  File "main.py", line 56, in main
  File "/flash/lib/ds18x20_single.py", line 14, in __init__
AssertionError: Not (only) one sensor on the bus
